name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  app_links: ^6.4.1
  flutter_svg: ^2.2.4
  permission_handler: ^12.0.1

  trezor_flutter:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/device_trezor_model_one.svg
     - assets/device_trezor_model_t.svg
     - assets/device_trezor_safe_3.svg
     - assets/device_trezor_safe_5.svg
     - assets/device_trezor_safe_7.svg
