name: trezor_flutter
description: A Flutter plugin to scan, connect & sign transactions using your Trezor devices
version: 0.1.0
repository: https://github.com/cake-tech/trezor-flutter
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  universal_platform: ^1.1.0
  universal_ble: ^1.2.0
  trezor_usb_transport:
    path: ../trezor_usb_transport
#    git:
#      url: git@github.com:cake-tech/trezor-flutter.git
#      path: trezor_usb_transport
  rxdart: ^0.28.0
  collection: ^1.18.0
  protobuf: ^3.1.0
  fixnum: ^1.1.1
  pointycastle: ^3.7.3
  fast_base58: ^0.2.1

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^4.0.0
  test: ^1.31.0

flutter:

platforms:
  android:
  ios:
  web:
